import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import LogoutBtn from "./LogOutBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import DarkMode from "./DarkMode";
const inter = Inter({ subsets: ["latin"] });
import { cookies } from "next/headers";

let cookie = cookies().get("mode");

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    let session = await getServerSession(authOptions);
    return (
        <html lang="en">
            <body
                className={
                    cookie != undefined && cookie.value == "dark"
                        ? "dark-mode"
                        : "white-mode"
                }
            >
                <div className="navbar">
                    <Link href="/" className="logo">
                        Appleforum
                    </Link>
                    <Link href="/register">register</Link>
                    <Link href="/list">List</Link>
                    <Link href="/write">Write</Link>
                    <DarkMode></DarkMode>
                    {session ? (
                        <span>
                            {session.user.name} <LogoutBtn></LogoutBtn>
                        </span>
                    ) : (
                        <LoginBtn></LoginBtn>
                    )}
                </div>
                {children}
            </body>
        </html>
    );
}
